### ISSUE TITLE
How to use this tool ?

### ISSUE THREAD

**Issue by jooola** [go-semantic-release/semantic-release#123]
I've been browsing the different repository to try finding documentation on how to configure or do some task. And I didn't find much documentation.

For instance I was hoping to upload the generated change log back to github from the github actions. But I couldn't find any doc to guide me.

Also I would like to release a version only by manually triggering the CI. Is there a way to do this ?

Did I miss a documentation link somewhere ?

**Comment by jooola** [comment]
Maybe I am asking for feature that aren't yet implemented. Is there a roadmap / epic somewhere in the project that could describe it's plans for the future ?

This tool is great idea btw !

**Comment by christophwitzko** [comment]
Hi @jooola, thanks for giving semantic-release a try, and sorry for the non-existing documentation. 😇
If you use GitHub + GitHub actions you should have a look the [go-semantic-release/action](https://github.com/go-semantic-release/action) repository.
With the default configuration, the changelog will be uploaded automatically to GitHub. (I am also not entirely sure if I understand your issue correctly)

To enable manually triggered releases, you would need to configure GitHub Actions with the [`if` conditional](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idif) or setup a separate release job with the [`workflow_dispatch`](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) event.

Cheers, Chris

**Comment by jooola** [comment]
@christophwitzko Thanks for the feedback.

I would like to upload a CHANGELOG.md file generated by the CI back to the repository. I probably didn't explain my use case enough sorry.

Thanks for the tips. Maybe starting to write a FAQ or enabling discussions/question labels will provide some help for new comers ?

**Comment by jooola** [comment]
I guess the main trouble I have is to know what are the input/output of this tool. If I know if a CHANGELOG.md file get's generated, I could use some other actions/git to push it back to the repo.

**Comment by christophwitzko** [comment]
Thank you for clarifying. I like the idea to use question labels 👍 

You can use the `changelog-file` options to generate the `CHANGELOG.md`.

```yaml
- uses: go-semantic-release/action@v1
   id: semrel
   with:
     github-token: ${{ secrets.GITHUB_TOKEN }}
     changelog-file: "CHANGELOG.md"
```

**Comment by biodrone** [comment]
Came across this whilst trying to figure out why my changelog isn't actually being generated... My step is below, it works for versioning and tagging, but it never produces an actual changelog file. I've tried manually creating it just in case but to no avail. I can see from my logs that it's outputting that a changelog is being generated but still nothing... Am I just being dense or is there some other setting needed to allow semrel to update the file and commit back?

```YAML
- name: Version
        uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          force-bump-patch-version: true
          changelog-generator-opt: "emojis=true"
          changelog-file: "CHANGELOG.md"
          prepend: true
```

Log output:
![image](https://user-images.githubusercontent.com/1135584/147852248-5bfcd378-2290-4075-8202-dedff23dd5fa.png)

**Comment by soderluk** [comment]
@biodrone I was wondering exactly the same, but the CHANGELOG.md is generated and added to the release archive.
I'm looking for having the actual CHANGELOG.md added in the repo root, containing all the changes in the repo. Currently only the release archive has the CHANGELOG.md which only shows the changes between the previous release and the current release.

@christophwitzko does the below configuration actually update an existing CHANGELOG.md in the repo root?
```yaml
- uses: go-semantic-release/action@v1
   id: semrel
   with:
     github-token: ${{ secrets.GITHUB_TOKEN }}
     changelog-file: "CHANGELOG.md"
```
or is this also just going to add the CHANGELOG.md to the release archive?

I found in another repo this .goreleaser.yaml configuration:
```yaml
version: 2

...

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
```
I wonder if go-semantic-release supports this? And will this generate the CHANGELOG.md in the repo root.
