### ISSUE TITLE
Flag '--update' and '-u' are seem not working

### ISSUE THREAD

**Issue by ted-vo** [go-semantic-release/semantic-release#137]
Hi!
I just create custom plugin [files-updater-gradle](https://github.com/ted-vo/files-updater-gradle)
So I want to use `--update` for my `gradle.properties` file.

**Expected behavior:**
It should pass `--update` value to `conf.UpdateFiles`

**Actual behavior:**
`conf.UpdateFiles` with no data

----------------------------------------------------------------------------------------------------------
**Try to debug:**

I found the code condition here for the `--update` flag.

https://github.com/go-semantic-release/semantic-release/blob/18e8bae821ffac4f4569bc642ae3cb29ecf983f6/cmd/semantic-release/main.go#L292

I found the `--update` flag get value here:
https://github.com/go-semantic-release/semantic-release/blob/18e8bae821ffac4f4569bc642ae3cb29ecf983f6/pkg/config/config.go#L118

So I try to debug by re-build with some log. You can see it in the picture.

<img width="604" alt="image" src="https://user-images.githubusercontent.com/11543501/161806316-698b6dcd-ccc6-44ef-b8e5-90036f687ad6.png">
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/11543501/161806584-196e48a1-df8f-462e-9070-663988b94347.png">

Result of my command

<img width="898" alt="image" src="https://user-images.githubusercontent.com/11543501/161805080-173b2599-6771-4c5d-bc43-ee748e5c4da5.png">

p/s: Sorry because English is not my primary language.

**Comment by a5r0n** [comment]
same from gh-action
``` yaml
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          changelog-generator-opt: "emojis=true"
          allow-initial-development-versions: true
          force-bump-patch-version: true
          prerelease: ${{ github.event_name == 'pull_request' }}
          changelog-file: CHANGELOG.md
          update-file: .version
```
