### ISSUE TITLE
Docs improvements

### ISSUE THREAD

**Issue by jtuchel** [go-semantic-release/semantic-release#146]
I created a new go project with the following workflow to play around

```yml
name: Release on push on main branch

on:
  push:
    branches:
      - 'main'

jobs:
  release-on-push-on-main-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: "CHANGELOG.md"
```

For now that's it, I'm just pushing to the main branch to see what it does :)

Unfortunately I'm struggling with the docs:

- I couldn't find a `v2` action ( tried it in the workflow but Github couldn't find it ) which is mentioned at https://github.com/go-semantic-release/semantic-release#plugin-system
- The arguments ( https://github.com/go-semantic-release/action#arguments ) need examples or at least datatypes. Does `changelog-file` expect `true`, `CHANGELOG.md` or ( the correct one ) `"CHANGELOG.md"`? I think it would be nice to pass `true` to the action if you want that changelog file and the default name is similiar to the semantic-release npm package. But you can change the name if you want.
- The workflow above does not generate a changelog. I would expect a "semantic-release" bot to create a file and push changes to it
- Does go-semantic-release prefer npm projects? I'm asking this because the docs provide an example for npm projects https://github.com/go-semantic-release/action#example-ciyml-for-an-npm-package and the action logged

> [go-semantic-release]: warning: file update plugins found but no files marked for update. You may be missing the update flag, e.g. --update package.json

Thanks in advance
