### ISSUE TITLE
Bug: the pipelines being run aren't updating the semantic tag version (possibly dependabot releated)

### ISSUE THREAD

**Issue by Will-Mann-16** [go-semantic-release/semantic-release#172]
Hi guys,

Love the work you've done with the library. However we recently we're having issues recently after enabling dependabot with some of our commits. The pipelines now will run, but won't release a new version _at all_. As you can see below, the red arrow indicates the last release and the actions on the pipeline are showing the release pipeline (all pass).

Feel free to look at the library here: [https://www.github.com/ls6-events/astra](https://www.github.com/ls6-events/astra) for more detailed logging.

![CleanShot 2024-01-28 at 22 32 33](https://github.com/go-semantic-release/semantic-release/assets/7892675/01acb3f8-de3b-4309-9e6f-a5acecd1138f)

And this is our pipeline output for the most recent run (specifically the `release` job):

```bash
Run go-semantic-release/action@v1
downloading semantic-release binary...
running semantic-release...
/home/runner/work/_temp/7[6](https://github.com/LS6-Events/astra/actions/runs/7632591943/job/20793178009#step:4:7)634c[7](https://github.com/LS6-Events/astra/actions/runs/7632591943/job/20793178009#step:4:8)b-ddcc-4cf7-a27f-3[8](https://github.com/LS6-Events/astra/actions/runs/7632591943/job/20793178009#step:4:9)dcf55eff78 --version-file --changelog .generated-go-semantic-release-changelog.md --hooks goreleaser
[go-semantic-release]: version: 2.2[9](https://github.com/LS6-Events/astra/actions/runs/7632591943/job/20793178009#step:4:10).0
[go-semantic-release]: trying to prefetch plugins...
[go-semantic-release]: all plugins were prefetched!
[go-semantic-release]: ci-condition plugin: GitHub Actions@1.9.0
[go-semantic-release]: provider plugin: GitHub@1.16.0
[go-semantic-release]: getting default branch...
[go-semantic-release]: found default branch: main
[go-semantic-release]: found current branch: main
[go-semantic-release]: found current sha: 9162c781bd9bb9f968fcef1e60f40c9fff0d8af6
[go-semantic-release]: hooks plugins: GoReleaser@1.9.0
[go-semantic-release]: running CI condition...
[go-semantic-release]: getting latest release...
[go-semantic-release]: found version: 1.22.0
[go-semantic-release]: getting commits...
[go-semantic-release]: analyzing commits...
[go-semantic-release]: commit-analyzer plugin: default@1.[12](https://github.com/LS6-Events/astra/actions/runs/7632591943/job/20793178009#step:4:13).0
[go-semantic-release]: calculating new version...
[go-semantic-release]: no change
[go-semantic-release]: stopping plugins...
```

The actions yaml is here:

```yaml
name: CI
on:
  push:
    branches:
      - 'main'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.1
          args: --timeout=10m --config=.golangci.yml
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - run: go test -v ./...
  release:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

We suspect dependabot, but we don't entirely know. This has been happening across our repos soon after we enable dependabot but we did it all quite recently so it could be something else.

Thanks!
